In [4]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from fractions import Fraction
%matplotlib inline
from sklearn.datasets import load_iris

## Question 1.

In [14]:
space=14

p_sunny=5/14
p_play=9/14
p_play_intersection_s=3/14
p_playIsunny='%.3f'%(p_play_intersection_s/p_sunny )
print("Probability of Playing when sunny is ",Fraction(p_playIsunny))


Probability of Playing when sunny is  3/5


## Question 2.

In [23]:
iris=load_iris()

print(iris.data)
print(iris.target)
d=iris.data
t=iris.target

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [24]:
from sklearn.model_selection import train_test_split as  ttl
train_x,test_x,train_y,test_y=ttl(d,t,test_size=0.2)



##  GNB

In [25]:
from sklearn.naive_bayes import GaussianNB
model_GNB=GaussianNB()

model_GNB.fit(train_x,train_y)

GaussianNB(priors=None)

In [26]:
prediction_GNB=model_GNB.predict(test_x)

In [27]:
results_GNB=pd.DataFrame({'Prediction':prediction_GNB,'Actual':test_y})
print(results_GNB)

    Prediction  Actual
0            2       1
1            0       0
2            1       1
3            2       2
4            1       1
5            1       1
6            1       1
7            0       0
8            0       0
9            2       2
10           1       2
11           2       2
12           2       2
13           2       2
14           2       2
15           0       0
16           2       2
17           1       1
18           2       2
19           0       0
20           0       0
21           0       0
22           1       2
23           1       1
24           2       2
25           1       1
26           1       1
27           1       1
28           2       2
29           2       2


## MNB

In [28]:
from sklearn.naive_bayes import MultinomialNB
model_MNB=MultinomialNB()

model_MNB.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
prediction_MNB=model_MNB.predict(test_x)

In [30]:
results_MNB=pd.DataFrame({'Prediction':prediction_MNB,'Actual':test_y})
print(results_MNB)

    Prediction  Actual
0            1       1
1            0       0
2            1       1
3            1       2
4            1       1
5            1       1
6            1       1
7            0       0
8            0       0
9            1       2
10           1       2
11           1       2
12           2       2
13           1       2
14           2       2
15           0       0
16           1       2
17           1       1
18           1       2
19           0       0
20           0       0
21           0       0
22           1       2
23           1       1
24           2       2
25           1       1
26           1       1
27           1       1
28           2       2
29           2       2


In [31]:
from sklearn.metrics import r2_score,confusion_matrix,classification_report

### Confusion matrix and Classification Report  GNB

In [32]:
print(confusion_matrix(test_y,prediction_GNB))

[[ 7  0  0]
 [ 0  9  1]
 [ 0  2 11]]


In [33]:

print(r2_score(test_y, prediction_GNB))

0.8404255319148937


In [34]:
print(classification_report(test_y, prediction_GNB))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       0.82      0.90      0.86        10
          2       0.92      0.85      0.88        13

avg / total       0.90      0.90      0.90        30



### Confusion matrix and Classification Report  MNB

In [17]:
print(confusion_matrix(test_y,prediction_MNB))

[[ 8  0  0]
 [ 0 11  1]
 [ 0  0 10]]


In [16]:

print(r2_score(test_y, prediction_MNB))

0.9440298507462687


In [20]:
print(classification_report(test_y, prediction_MNB))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       1.00      0.92      0.96        12
          2       0.91      1.00      0.95        10

avg / total       0.97      0.97      0.97        30

